### ISSUE TITLE
Identify where we can down the stock list in BSE website

### ISSUE THREAD

**Issue by RamCodz** [RamCodz/StreamlitStockView#1]
As per the requirement, we need to use a sheet of stocks list which will have ticker name, stock name, face value, sector, industry details.

Analyse and find from where we can download this sheet from BSE website regularly.

**Comment by Desingu** [comment]
https://www.bseindia.com/corporates/List_Scrips.html
Select Segment as 'Equity T+1' and Status as 'Active' then click on the Download button which is there in the right side of 'List Of Securities' label.

**Comment by RamCodz** [comment]
Did you verified it's giving all the columns like the sheet I shared.

**Comment by RamCodz** [comment]
completed, we can download this data from BSE website.
